services:

  # HOMEPAGE
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    restart: unless-stopped
    env_file:
      - ../management/.env
      - ./.env
    environment:
      # https://gethomepage.dev/installation/#homepage_allowed_hosts
      HOMEPAGE_ALLOWED_HOSTS: 192.168.2.2:3000,home.home.arpa,home.homelab.local

      # Required fields in './.env':
      # HOMEPAGE_VAR_PIHOLE_KEY                       = Pi-Hole widget API key
      # HOMEPAGE_VAR_GOOGLE_CALENDAR_ICAL_PRIVATE_URL = Calendar widget
      # HOMEPAGE_VAR_MINECRAFT_SERVER_IP              = Minecraft server widget
      # HOMEPAGE_VAR_JELLYFIN_API_KEY                 = Jellyfin widget API key
      # HOMEPAGE_VAR_TAILSCALE_ACCESS_TOKEN           = Tailscale widget access token
      # HOMEPAGE_VAR_SONARR_API_KEY                   = Sonarr widget API key
      # HOMEPAGE_VAR_RADARR_API_KEY                   = Radarr widget API key
      # HOMEPAGE_VAR_PROWLARR_API_KEY                 = Prowlarr widget API key
      # HOMEPAGE_VAR_JELLYSEERR_API_KEY               = Jellyseerr widget API key
      # HOMEPAGE_VAR_SABNZBD_API_KEY                  = Sabnzbd widget API key
    ports:
      - 3000:3000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./homepage/config:/app/config
      - ./homepage/images:/app/public/images
    networks:
      - frontend

  # STATISTICS FOR STRAVA
  statistics_for_strava:
    image: robiningelbrecht/strava-statistics:latest
    container_name: statistics_for_strava
    restart: unless-stopped
    env_file: ./.env
    environment:
      TZ: Europe/Warsaw
      PUID: 1000
      PGID: 1000
      # PROXY_HOST: strava.home.arpa # (maybe not necessary if using my own caddy reverse proxy)
      # PROXY_PORT: 8082

      # Required fields in './.env':
      # STRAVA_CLIENT_ID     = Strava API client ID
      # STRAVA_CLIENT_SECRET = Strava API client secret
      # STRAVA_REFRESH_TOKEN = Statistics for Strava refresh token
    ports:
      - 8082:8080
    volumes:
      - ./statistics_for_strava/config:/var/www/config/app
      - sfs_build:/var/www/build
      - sfs_db:/var/www/storage/database
      - sfs_files:/var/www/storage/files
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:2019/metrics"]
      start_period: 60s
    networks:
      - statistics_for_strava_net
      - frontend

  statistics_for_strava_daemon:
    image: robiningelbrecht/strava-statistics:latest
    container_name: statistics_for_strava_daemon
    restart: unless-stopped
    env_file: ./.env
    environment:
      TZ: Europe/Warsaw
      PUID: 1000
      PGID: 1000
      # PROXY_HOST: strava.home.arpa # (maybe not necessary if using my own caddy reverse proxy)
      # PROXY_PORT: 8082

      # Required fields in './.env':
      # STRAVA_CLIENT_ID     = Strava API client ID
      # STRAVA_CLIENT_SECRET = Strava API client secret
      # STRAVA_REFRESH_TOKEN = Statistics for Strava refresh token
    volumes_from:
      - statistics_for_strava
    depends_on:
      - statistics_for_strava
    healthcheck:
      test: [ "CMD", "sh", "-c", "test -f /var/www/storage/database/strava.db && echo 'ok' || exit 1" ]
      start_period: 5s
    entrypoint: ['bin/console', 'app:daemon:run']
    networks:
      - statistics_for_strava_net

networks:
  frontend:
    name: frontend
    external: true
  statistics_for_strava_net:

volumes:
  sfs_build:
  sfs_db:
  sfs_files:
