services:

  # HOMEPAGE
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    restart: unless-stopped
    env_file:
      - ../management/.env
      - ./.env
    environment:
      # https://gethomepage.dev/installation/#homepage_allowed_hosts
      HOMEPAGE_ALLOWED_HOSTS: 192.168.2.2:3000,home.home.arpa,home.homelab.local

      # Required fields in './.env':
      # HOMEPAGE_VAR_PIHOLE_KEY                       = Pi-Hole widget API key
      # HOMEPAGE_VAR_GOOGLE_CALENDAR_ICAL_PRIVATE_URL = Calendar widget
      # HOMEPAGE_VAR_MINECRAFT_SERVER_IP              = Minecraft server widget
      # HOMEPAGE_VAR_JELLYFIN_API_KEY                 = Jellyfin widget API key
      # HOMEPAGE_VAR_TAILSCALE_ACCESS_TOKEN           = Tailscale widget access token
      # HOMEPAGE_VAR_SONARR_API_KEY                   = Sonarr widget API key
      # HOMEPAGE_VAR_RADARR_API_KEY                   = Radarr widget API key
      # HOMEPAGE_VAR_PROWLARR_API_KEY                 = Prowlarr widget API key
      # HOMEPAGE_VAR_JELLYSEERR_API_KEY               = Jellyseerr widget API key
      # HOMEPAGE_VAR_SABNZBD_API_KEY                  = Sabnzbd widget API key
      # HOMEPAGE_VAR_DOCKHAND_USERNAME                = Dockhand username
      # HOMEPAGE_VAR_DOCKHAND_PASSWORD                = Dockhand password
    ports:
      - 3000:3000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./homepage/config:/app/config
      - ./homepage/images:/app/public/images
    networks:
      - frontend

  # STATISTICS FOR STRAVA
  statistics_for_strava:
    image: robiningelbrecht/strava-statistics:latest
    container_name: statistics_for_strava
    restart: unless-stopped
    env_file: ./.env
    environment:
      TZ: Europe/Warsaw
      PUID: 1000
      PGID: 1000
      # PROXY_HOST: strava.home.arpa # (maybe not necessary if using my own caddy reverse proxy)
      # PROXY_PORT: 8082

      # Required fields in './.env':
      # STRAVA_CLIENT_ID     = Strava API client ID
      # STRAVA_CLIENT_SECRET = Strava API client secret
      # STRAVA_REFRESH_TOKEN = Statistics for Strava refresh token
    ports:
      - 8082:8080
    volumes:
      - ./statistics_for_strava/config:/var/www/config/app
      - sfs_build:/var/www/build
      - sfs_db:/var/www/storage/database
      - sfs_files:/var/www/storage/files
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:2019/metrics"]
      start_period: 60s
    networks:
      - statistics_for_strava_net
      - frontend

  statistics_for_strava_daemon:
    image: robiningelbrecht/strava-statistics:latest
    container_name: statistics_for_strava_daemon
    restart: unless-stopped
    env_file: ./.env
    environment:
      TZ: Europe/Warsaw
      PUID: 1000
      PGID: 1000
      # PROXY_HOST: strava.home.arpa # (maybe not necessary if using my own caddy reverse proxy)
      # PROXY_PORT: 8082

      # Required fields in './.env':
      # STRAVA_CLIENT_ID     = Strava API client ID
      # STRAVA_CLIENT_SECRET = Strava API client secret
      # STRAVA_REFRESH_TOKEN = Statistics for Strava refresh token
    volumes_from:
      - statistics_for_strava
    depends_on:
      - statistics_for_strava
    healthcheck:
      test: [ "CMD", "sh", "-c", "test -f /var/www/storage/database/strava.db && echo 'ok' || exit 1" ]
      start_period: 5s
    entrypoint: ['bin/console', 'app:daemon:run']
    networks:
      - statistics_for_strava_net

  # YOUR SPOTIFY
  your_spotify_server:
    image: yooooomi/your_spotify_server
    container_name: your_spotify_server
    restart: unless-stopped
    ports:
      - 8083:8080
    links:
      - your_spotify_db
    depends_on:
      - your_spotify_db
    env_file: ./.env
    environment:
      TIMEZONE: Europe/Warsaw
      API_ENDPOINT: "${YOURSPOTIFY_ENDPOINT}" # This MUST be included as a valid URL in the spotify dashboard
      CLIENT_ENDPOINT: "${YOURSPOTIFY_ENDPOINT}"
      MONGO_ENDPOINT: mongodb://your_spotify_db:27017/your_spotify
      CORS: "${YOURSPOTIFY_ENDPOINT}"

      # Required fields in './.env':
      # SPOTIFY_PUBLIC   = Obtained on spotify.dev
      # SPOTIFY_SECRET   = Obtained on spotify.dev
      # YOURSPOTIFY_ENDPOINT = The URL where "yourspotify" service will be available
    networks:
      frontend:
      your_spotify_net:
      wireguard_net:
        ipv4_address: 172.24.0.6

  your_spotify_db:
    image: mongo:6
    container_name: your_spotify_db
    restart: unless-stopped
    volumes:
      - your_spotify_db:/data/db
    networks:
      - your_spotify_net

  your_spotify_client:
    image: yooooomi/your_spotify_client
    container_name: your_spotify_client
    restart: unless-stopped
    ports:
      - 3001:3000
    env_file: ./.env
    environment:
      TIMEZONE: Europe/Warsaw
      API_ENDPOINT: "${YOURSPOTIFY_ENDPOINT}"
    networks:
      - your_spotify_net
      - frontend

networks:
  frontend:
    name: frontend
    external: true
  wireguard_net:
    name: wireguard_exposed
    external: true
  statistics_for_strava_net:
    name: statistics_for_strava_net
  your_spotify_net:
    name: your_spotify_net

volumes:
  sfs_build:
  sfs_db:
  sfs_files:
  your_spotify_db:
    name: your_spotify_db
