services:

  # HOMEPAGE
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    restart: unless-stopped
    env_file:
      - ../management/.env
      - ./.env
    environment:
      # https://gethomepage.dev/installation/#homepage_allowed_hosts
      HOMEPAGE_ALLOWED_HOSTS: 192.168.2.2:3000,home.home.arpa,home.homelab.local

      # Required fields in './.env':
      # HOMEPAGE_VAR_PIHOLE_KEY                       = Pi-Hole widget API key
      # HOMEPAGE_VAR_GOOGLE_CALENDAR_ICAL_PRIVATE_URL = Calendar widget
      # HOMEPAGE_VAR_MINECRAFT_SERVER_IP              = Minecraft server widget
    ports:
      - 3000:3000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./homepage/config:/app/config
      - ./homepage/images:/app/public/images
    networks:
      - frontend

networks:
  frontend:
    name: frontend
    external: true

volumes:
  homepage:
