services:
  dockge:
    image: cmcooper1980/dockge
    container_name: dockge
    restart: always
    ports:
      - 9443:5001
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - dockge:/app/data
      # Stacks Directory
      # ⚠️ READ IT CAREFULLY. If you did it wrong, your data could end up writing into a WRONG PATH.
      # ⚠️ 1. FULL path only. No relative path (MUST)
      # ⚠️ 2. Left Stacks Path === Right Stacks Path (MUST)
      - /home/olo/home-server/stacks:/home/olo/home-server/stacks
    environment:
      - DOCKGE_STACKS_DIR=/home/olo/home-server/stacks
    networks:
      - frontend

volumes:
  dockge:

networks:
  frontend:
    name: frontend
    driver: bridge