services:
  portainer:
    container_name: portainer
    image: portainer/portainer-ce:lts
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    ports:
      - 9443:9443
    networks:
      - frontend

volumes:
  portainer_data:
    name: portainer_data

networks:
  frontend:
    name: frontend
    driver: bridge