services:

  # JELLYFIN
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    restart: unless-stopped
    user: 1000:1000 # instead of root
    group_add:
      - 1001 # storage group
    ports:
      - 8096:8096/tcp
      - 7359:7359/udp
    volumes:
      - jellyfin_cache:/cache
      - jellyfin_data:/config
      - ./jellyfin/config/config:/config/config
      - ./jellyfin/config/plugins:/config/plugins
      - ./jellyfin/config/root:/config/root
      - ./jellyfin/logs:/config/log
      - type: bind
        source: /srv/storage/Streaming/Media
        target: /media
      # Optional - extra fonts to be used during transcoding with subtitle burn-in
      # - type: bind
      #   source: /path/to/fonts
      #   target: /usr/local/share/fonts/custom
      #   read_only: true
    networks:
      - frontend
      - tailscale_net
      - streaming_net

  # SONARR
  sonarr:
    image: ghcr.io/linuxserver/sonarr:latest
    container_name: sonarr
    group_add:
      - 1001 # storage group
    ports:
      - 8989:8989
    volumes:
      - sonarr_config:/config
      - /srv/storage/Streaming:/data
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Europe/Warsaw
    restart: unless-stopped
    networks:
      - frontend
      - streaming_net

networks:
  frontend:
    name: frontend
    external: true
  tailscale_net:
    name: tailscale_exposed
    external: true
  streaming_net:
    name: streaming_net

volumes:
  jellyfin_cache:
    name: jellyfin_cache
  jellyfin_data:
    name: jellyfin_data
  sonarr_config:
    name: sonarr_config
