services:

  # JELLYFIN (media player)
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    restart: unless-stopped
    group_add:
      - 1001 # storage group
    ports:
      - 8096:8096/tcp
      - 7359:7359/udp
    volumes:
      - jellyfin_cache:/cache
      - jellyfin_data:/config
      - ./jellyfin/logs:/config/log
      - type: bind
        source: /mnt/nas/streaming/Media
        target: /media
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Europe/Warsaw
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: all
    networks:
      frontend:
      streaming_net:
      external_access_net:
        ipv4_address: 172.24.0.8
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [all]

  # SONARR (tv series manager)
  sonarr:
    image: ghcr.io/linuxserver/sonarr:latest
    container_name: sonarr
    restart: unless-stopped
    group_add:
      - 1001 # storage group
    ports:
      - 8989:8989
    volumes:
      - sonarr_config:/config
      - /mnt/nas/streaming:/data
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Europe/Warsaw
    networks:
      - frontend
      - streaming_net

  # RADARR (movie manager)
  radarr:
    image: ghcr.io/linuxserver/radarr:latest
    container_name: radarr
    restart: unless-stopped
    group_add:
      - 1001 # storage group
    ports:
      - 7878:7878
    volumes:
      - radarr_config:/config
      - /mnt/nas/streaming:/data
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Europe/Warsaw
    networks:
      - frontend
      - streaming_net

  # PROWLARR (indexer manager)
  prowlarr:
    image: ghcr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    restart: unless-stopped
    ports:
      - 9696:9696
    volumes:
      - prowlarr_config:/config
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Europe/Warsaw
    networks:
      - frontend
      - streaming_net

  # SEERR (request manager)
  seerr:
    image: ghcr.io/seerr-team/seerr:latest
    container_name: seerr
    restart: unless-stopped
    init: true
    ports:
      - 5055:5055
    volumes:
      - seerr_config:/app/config
      - ./seerr/logs:/app/config/logs
    environment:
      TZ: Europe/Warsaw
      LOG_LEVEL: debug
    networks:
      - frontend
      - streaming_net
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:5055/api/v1/settings/public || exit 1
      start_period: 20s
      timeout: 3s
      interval: 15s
      retries: 3

  # SABNZBD (usenet downloader)
  sabnzbd:
    image: ghcr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    restart: unless-stopped
    group_add:
      - 1001 # storage group
    ports:
      - 8081:8080
    volumes:
      - sabnzbd_config:/config
      - /mnt/nas/streaming/Downloads:/data/downloads
    environment:
      PUID: 1000
      PGID: 1000
    networks:
      - frontend
      - streaming_net

networks:
  frontend:
    name: frontend
    external: true
  external_access_net:
    name: external_access_net
    external: true
  streaming_net:
    name: streaming_net

volumes:
  jellyfin_cache:
    name: jellyfin_cache
  jellyfin_data:
    name: jellyfin_data
  sonarr_config:
    name: sonarr_config
  radarr_config:
    name: radarr_config
  prowlarr_config:
    name: prowlarr_config
  seerr_config:
    name: seerr_config
  sabnzbd_config:
    name: sabnzbd_config
