services:

  # MARK: CADDY (REVERSE PROXY)
  caddy:
    build:
      dockerfile: ./caddy/Dockerfile
      context: ./
    container_name: caddy
    restart: unless-stopped
    ports:
      # <host-port>:<container-port>
      - "80:80"
      - "443:443"
      - "443:443/udp"
    env_file:
      - ./.env
      # Required fields in './.env':
      # OVH_APPLICATION_KEY    = Generated in OVH dashboard, required for TLS challenge (HTTPS).
      # OVH_APPLICATION_SECRET = Generated in OVH dashboard, required for TLS challenge (HTTPS).
      # OVH_CONSUMER_KEY       = Generated in OVH dashboard, required for TLS challenge (HTTPS).
      # EXTERNAL_DOMAIN        = The domain used for SSL and external access.
    volumes:
      - ./caddy/config:/etc/caddy
      - ./caddy/logs:/logs
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - frontend

  # MARK: PI-HOLE (ADBLOCK + DNS SERVER)
  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    restart: unless-stopped
    depends_on:
      pihole_init:
        condition: service_completed_successfully
    ports:
      - 53:53/tcp # DNS TCP
      - 53:53/udp # DNS UDP
      - 82:80/tcp # HTTP access to admin dashboard
      - 444:443/tcp # HTTPS access to admin dashboard
    env_file:
      - ./.env
      # Required fields in './.env':
      # FTLCONF_webserver_api_password = Password for the admin dashboard, required for API access.
    environment:
      TZ: Europe/Warsaw
      FTLCONF_dns_listeningMode: 'ALL'
      FTLCONF_misc_etc_dnsmasq_d: 'true'
    volumes:
      - pihole_data:/etc/pihole
      - pihole_config:/etc/dnsmasq.d
    networks:
      - frontend
    # cap_add:
      # - SYS_NICE

  pihole_init:
    image: alpine
    container_name: pihole_init
    restart: no
    env_file:
      - ./pihole/.env
      # Required fields in './pihole/.env':
      # EXTERNAL_DOMAIN = The domain used for SSL and external access.
    volumes:
      - ./pihole/config/dnsmasq.d/wildcard-internal.conf.template:/templates/wildcard-internal.conf.template:ro
      - pihole_config:/output
    entrypoint: ["/bin/sh", "-c"]
    command:
      - |
        apk add --no-cache gettext-envsubst
        envsubst < /templates/wildcard-internal.conf.template > /output/wildcard-internal.conf
    network_mode: host

  newt:
    image: fosrl/newt
    container_name: newt
    restart: unless-stopped
    env_file:
      - ./newt/.env
    networks:
      - external_access_net

networks:
  frontend:
    name: frontend
  external_access_net:
    name: external_access_net
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.24.0.0/16
          gateway: 172.24.0.1

volumes:
  caddy_data:
    name: caddy_data
  caddy_config:
    name: caddy_config
  pihole_data:
    name: pihole_data
  pihole_config:
    name: pihole_config
