services:

  # CADDY (REVERSE PROXY)
  caddy:
    image: caddy:latest
    container_name: caddy
    restart: unless-stopped
    ports:
      # <host-port>:<container-port>
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./caddy/config:/etc/caddy
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - frontend

  # PI-HOLE (ADBLOCK + DNS SERVER)
  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    restart: unless-stopped
    ports:
      - 53:53/tcp # DNS TCP
      - 53:53/udp # DNS UDP
      - 82:80/tcp # HTTP access to admin dashboard
      - 444:443/tcp # HTTPS access to admin dashboard
    env_file:
      - ./.env
    environment:
      TZ: Europe/Warsaw
      FTLCONF_dns_listeningMode: 'ALL'
      FTLCONF_misc_etc_dnsmasq_d: 'true'
    volumes:
      - pihole:/etc/pihole
      # Track configuration files with git
      - ./pihole/dnsmasq.d:/etc/dnsmasq.d
    networks:
      - frontend
    # cap_add:
      # - SYS_NICE

  # TAILSCALE (EXTERNAL ACCESS)
  # docs:
  # - https://tailscale.com/docs/features/tailscale-services#step-3-create-a-service-proxy
  # - https://tailscale.com/docs/reference/tailscale-services-configuration-file
  # - https://tailscale.com/docs/features/containers/docker
  tailscale:
    image: tailscale/tailscale:latest
    container_name: tailscale
    restart: unless-stopped
    env_file:
      - ./.env
    environment:
      TZ: Europe/Warsaw
      TS_HOSTNAME: homelab
      TS_STATE_DIR: /var/lib/tailscale
      TS_EXTRA_ARGS: '--advertise-tags=tag:homelab'
      TS_SERVE_CONFIG: /etc/tailscale/services.json
      # TS_TAILSCALED_EXTRA_ARGS: '--config=/etc/tailscale/daemon.json' # does not work

      # Required fields in './.env':
      # TS_CLIENT_ID     = Generated as credential in Tailscale admin console
      # TS_CLIENT_SECRET = Generated as credential in Tailscale admin console
    volumes:
      - tailscale_data:/var/lib/tailscale
      - ./tailscale/config:/etc/tailscale
    devices:
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - NET_ADMIN
    entrypoint: /bin/sh -c "
      /usr/local/bin/containerboot &
      sleep 5;
      tailscale serve advertise svc:tv;
      tailscale serve advertise svc:requests;
      wait"
    # post_start:
    #   - command: sleep 15 && tailscale serve advertise svc:tv # does not work
        # user: root
    networks:
      - tailscale_net

networks:
  frontend:
    name: frontend
    external: true
  tailscale_net:
    name: tailscale_exposed

volumes:
  caddy_data:
  caddy_config:
  pihole:
  tailscale_data:
