services:

  # CADDY (REVERSE PROXY)
  caddy:
    build:
      dockerfile: ./caddy/Dockerfile
      context: ./
    container_name: caddy
    restart: unless-stopped
    ports:
      # <host-port>:<container-port>
      - "80:80"
      - "443:443"
      - "443:443/udp"
    env_file:
      - ./.env
      # Required fields in './.env':
      # OVH_APPLICATION_KEY    = Generated in OVH dashboard, required for TLS challenge (HTTPS).
      # OVH_APPLICATION_SECRET = Generated in OVH dashboard, required for TLS challenge (HTTPS).
      # OVH_CONSUMER_KEY       = Generated in OVH dashboard, required for TLS challenge (HTTPS).
      # EXTERNAL_DOMAIN        = The domain used for SSL and external access.
    volumes:
      - ./caddy/config:/etc/caddy
      - ./caddy/logs:/logs
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - frontend

  # PI-HOLE (ADBLOCK + DNS SERVER)
  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    restart: unless-stopped
    depends_on:
      pihole_init:
        condition: service_completed_successfully
    ports:
      - 53:53/tcp # DNS TCP
      - 53:53/udp # DNS UDP
      - 82:80/tcp # HTTP access to admin dashboard
      - 444:443/tcp # HTTPS access to admin dashboard
    env_file:
      - ./.env
      # Required fields in './.env':
      # FTLCONF_webserver_api_password = Password for the admin dashboard, required for API access.
    environment:
      TZ: Europe/Warsaw
      FTLCONF_dns_listeningMode: 'ALL'
      FTLCONF_misc_etc_dnsmasq_d: 'true'
    volumes:
      - pihole_data:/etc/pihole
      - pihole_config:/etc/dnsmasq.d
    networks:
      - frontend
    # cap_add:
      # - SYS_NICE

  pihole_init:
    image: alpine
    container_name: pihole_init
    restart: no
    env_file:
      - ./pihole/.env
      # Required fields in './pihole/.env':
      # EXTERNAL_DOMAIN = The domain used for SSL and external access.
    volumes:
      - ./pihole/config/dnsmasq.d/wildcard-internal.conf.template:/templates/wildcard-internal.conf.template:ro
      - pihole_config:/output
    entrypoint: ["/bin/sh", "-c"]
    command:
      - |
        apk add --no-cache gettext-envsubst
        envsubst < /templates/wildcard-internal.conf.template > /output/wildcard-internal.conf
    network_mode: host

  # TAILSCALE (EXTERNAL ACCESS)
  # docs:
  # - https://tailscale.com/docs/features/tailscale-services#step-3-create-a-service-proxy
  # - https://tailscale.com/docs/reference/tailscale-services-configuration-file
  # - https://tailscale.com/docs/features/containers/docker
  tailscale:
    image: tailscale/tailscale:latest
    container_name: tailscale
    restart: unless-stopped
    env_file:
      - ./.env
    environment:
      TZ: Europe/Warsaw
      TS_HOSTNAME: homelab
      TS_STATE_DIR: /var/lib/tailscale
      TS_EXTRA_ARGS: '--advertise-tags=tag:homelab'
      # TS_SERVE_CONFIG: /etc/tailscale/services.json

      # Required fields in './.env':
      # TS_CLIENT_ID     = Generated as credential in Tailscale admin console
      # TS_CLIENT_SECRET = Generated as credential in Tailscale admin console
    volumes:
      - tailscale_data:/var/lib/tailscale
      - ./tailscale/config:/etc/tailscale
    devices:
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - NET_ADMIN
    entrypoint: /bin/sh -c "
      (
        sleep 5;
        tailscale serve set-config --all /etc/tailscale/services.json;
      ) &
      exec /usr/local/bin/containerboot"
    # Workaround for services not being advertised on startup,
    # see: https://github.com/tailscale/tailscale/issues/18255.

    # TS_SERVE_CONFIG does not support the new serve config format.
    # This might be fixed in the future,
    # see: https://github.com/tailscale/tailscale/pull/18527.

    # `post_start` script cannot be used here, because it is a compose
    # feature and on host reboots is not considered by docker daemon.
    networks:
      - tailscale_net

  # WIREGUARD (OUTPOST ACCESS)
  wireguard:
    image: linuxserver/wireguard
    container_name: wireguard
    restart: unless-stopped
    environment:
      TZ: Europe/Warsaw
      PUID: 1000
      PGID: 1000
    volumes:
      - ./wireguard/config:/config
      - /lib/modules:/lib/modules
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
    networks:
      - wireguard_net
    healthcheck:
      test: ping -c 1 10.13.13.1 || exit 1
      interval: 30s
      timeout: 5s
      retries: 3

  caddy_wireguard:
    image: caddy:latest
    container_name: caddy_wireguard
    restart: unless-stopped
    volumes:
      - ./caddy_wireguard/config:/etc/caddy
      - caddy_wireguard_data:/data
      - caddy_wireguard_config:/config
    network_mode: "service:wireguard"
    depends_on:
      - wireguard


networks:
  frontend:
    name: frontend
  tailscale_net:
    name: tailscale_exposed
  wireguard_net:
    name: wireguard_exposed
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.24.0.0/16
          gateway: 172.24.0.1

volumes:
  caddy_data:
    name: caddy_data
  caddy_config:
    name: caddy_config
  pihole_data:
    name: pihole_data
  pihole_config:
    name: pihole_config
  tailscale_data:
    name: tailscale_data
  caddy_wireguard_data:
    name: caddy_wireguard_data
  caddy_wireguard_config:
    name: caddy_wireguard_config
