services:
  # FILEBROWSER
  filebrowser:
    image: gtstef/filebrowser:beta
    container_name: filebrowser
    restart: unless-stopped
    ports:
      - 8080:80
    volumes:
      - filebrowser_data:/home/filebrowser/data
      - ./filebrowser/config:/home/filebrowser/config
      - /mnt/nas/media:/srv/media
      - /mnt/nas/streaming:/srv/streaming
    environment:
      FILEBROWSER_CONFIG: config/config.yaml
    networks:
      - frontend

  duplicati:
    image: duplicati/duplicati:latest
    container_name: duplicati
    restart: unless-stopped
    volumes:
      - duplicati_data:/data
      - /mnt/backup:/backups
      - /home:/sources/home
      - /var/lib/docker/volumes:/sources/docker_volumes
    environment:
      SETTINGS_ENCRYPTION_KEY: "$$settings-key"
      DUPLICATI__SECRET_PROVIDER: file-secret:///run/secrets/duplicati_secrets
      DUPLICATI__WEBSERVICE_PASSWORD: "$$ui-password"
      DUPLICATI__WEBSERVICE_ALLOWED_HOSTNAMES: "backup.home.arpa"
    secrets:
      - duplicati_secrets
    networks:
      - frontend

networks:
  frontend:
    name: frontend
    external: true

volumes:
  filebrowser_data:
    name: filebrowser_data
  duplicati_data:
    name: duplicati_data

secrets:
  duplicati_secrets:
    file: ./duplicati/secrets.json
