services:
  # FILEBROWSER
  filebrowser:
    image: filebrowser/filebrowser:latest
    container_name: filebrowser
    restart: unless-stopped
    group_add:
      - 1001 # storage group
    ports:
      - 8080:80
    volumes:
      - /srv/storage:/srv # this should point to the storage location
      - filebrowser_data:/database
      - filebrowser_config:/config
      - ./filebrowser/customization:/config/branding # https://filebrowser.org/customization.html
    environment:
      # available env variables: https://filebrowser.org/cli/filebrowser.html#options
      FB_NOAUTH: true
      FB_USERNAME: File Browser
    networks:
      - frontend

networks:
  frontend:
    name: frontend
    external: true

volumes:
  filebrowser_data:
    name: filebrowser_data
  filebrowser_config:
    name: filebrowser_config
