---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/bookmarks

- Bookmarks:
    - Proton Mail:
        - icon: sh-proton-mail-light
          href: https://mail.proton.me/
    - Google Drive:
        - icon: sh-google-drive-light
          href: https://drive.google.com/drive/my-drive
    - Github:
        - icon: sh-github-light
          href: https://github.com/
    - Lichess:
        - icon: si-chessdotcom-#ffffff
          href: https://lichess.org/
    - Youtube:
        - icon: sh-youtube-light
          href: https://www.youtube.com/
    - Twitch:
        - icon: sh-twitch-light
          href: https://www.twitch.tv/

- Finance:
    - Zondacrypto:
        - icon: https://zondacrypto.com/o/bb-theme/images/appBar/app-icon.png
          abbr: ZC
          href: https://zondacrypto.com/
    - Obligacje Skarbowe:
        - icon: https://www.obligacjeskarbowe.pl/static/front/treasurybond/img/logo.svg
          abbr: OS
          href: https://www.obligacjeskarbowe.pl/
    - Binance:
        - icon: si-binance-#ffffff
          abbr: BN
          href: https://www.binance.com/en
    - XTB:
        - icon: https://companieslogo.com/img/orig/XTB.WA-435c9163.svg
          abbr: XT
          href: https://www.xtb.com/pl
    - Top Kantor:
        - icon: https://topkantor.pl/kantor/img/logo_small.png
          abbr: TK
          href: https://topkantor.pl/
    - JustETF:
        - icon: https://www.justetf.com/images/logo/justetf-logo.png?v2
          abbr: JE
          href: https://www.justetf.com/en/
    - MBank:
        - icon: https://companieslogo.com/img/orig/MBK.WA-b110662f.svg
          abbr: MB
          href: https://www.mbank.pl/
    - Revolut:
        - abbr: R
          href: https://www.revolut.com/

- Streaming:
    - Netflix:
        - icon: sh-netflix
          href: https://www.netflix.com/
    - Prime Video:
        - icon: sh-amazon-prime-video
          href: https://www.primevideo.com/
    - Disney+:
        - icon: sh-disney-plus
          href: https://www.disneyplus.com/
    - HBO Max:
        - icon: sh-hbo-max-light
          href: https://www.hbomax.com/
    - Apple TV+:
        - icon: sh-apple-tv-light
          href: https://tv.apple.com/

- Documentation:
    - Homepage:
        - icon: sh-homepage-light
          href: https://gethomepage.dev/configs/
    - Dockhand:
        - icon: sh-dockhand
          href: https://dockhand.pro/manual/
    - Pi-Hole:
        - icon: sh-pi-hole-light
          href: https://docs.pi-hole.net/
    - File Browser:
        - icon: sh-file-browser-light
          href: https://filebrowser.org/installation
    - Caddy:
        - icon: sh-caddy-light
          href: https://caddyserver.com/docs/
    - WireGuard:
        - icon: sh-wireguard-light
          href: https://hub.docker.com/r/linuxserver/wireguard/
    - Jellyfin:
        - icon: sh-jellyfin-light
          href: https://jellyfin.org/docs/
    - Statistics for Strava:
        - icon: sh-strava-light
          href: https://statistics-for-strava-docs.robiningelbrecht.be/#/
    - Your Spotify:
        - icon: sh-spotify-light
          href: https://github.com/Yooooomi/your_spotify
    - Tailscale:
        - icon: sh-tailscale-light
          href: https://tailscale.com/docs
    - Sonarr:
        - icon: sh-sonarr-light
          href: https://github.com/linuxserver/docker-sonarr
    - Radarr:
        - icon: sh-radarr-light
          href: https://github.com/linuxserver/docker-radarr
    - Prowlarr:
        - icon: sh-prowlarr-light
          href: https://github.com/linuxserver/docker-prowlarr
    - Jellyseerr:
        - icon: sh-jellyseerr-light
          href: https://docs.seerr.dev/
    - Sabnzbd:
        - icon: sh-sabnzbd-light
          href: https://sabnzbd.org/wiki/
    - Authentik:
        - icon: sh-authentik-light
          href: https://docs.goauthentik.io/
