---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/bookmarks

- Bookmarks:
    - Proton Mail:
        - icon: sh-proton-mail-light
          href: https://mail.proton.me/
    - Github:
        - icon: sh-github-light
          href: https://github.com/

- Documentation:
    - Homepage:
        - icon: sh-homepage-light
          href: https://gethomepage.dev/configs/
    - Dockhand:
        - icon: sh-dockhand
          href: https://dockhand.pro/manual/
    - Pi-Hole:
        - icon: sh-pi-hole-light
          href: https://docs.pi-hole.net/
    - File Browser:
        - icon: sh-file-browser-light
          href: https://filebrowser.org/installation
    - Caddy:
        - icon: sh-caddy-light
          href: https://caddyserver.com/docs/
    - Jellyfin:
        - icon: sh-jellyfin-light
          href: https://jellyfin.org/docs/
    - Statistics for Strava:
        - icon: sh-strava-light
          href: https://statistics-for-strava-docs.robiningelbrecht.be/#/
    - Your Spotify:
        - icon: sh-spotify-light
          href: https://github.com/Yooooomi/your_spotify
    - Sonarr:
        - icon: sh-sonarr-light
          href: https://github.com/linuxserver/docker-sonarr
    - Radarr:
        - icon: sh-radarr-light
          href: https://github.com/linuxserver/docker-radarr
    - Prowlarr:
        - icon: sh-prowlarr-light
          href: https://github.com/linuxserver/docker-prowlarr
    - Jellyseerr:
        - icon: sh-jellyseerr-light
          href: https://docs.seerr.dev/
    - Sabnzbd:
        - icon: sh-sabnzbd-light
          href: https://sabnzbd.org/wiki/
    - "Pangolin / Newt":
        - icon: sh-pangolin-light
          href: https://docs.pangolin.net/
    - Firefly III:
        - icon: sh-firefly-iii-light
          href: https://docs.firefly-iii.org/?mtm_kwd=top-link
