---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/services/

- Services:
    - Homelab:
        - Homepage:
            href: http://home.home.arpa
            icon: sh-homepage
            server: homelab
            container: homepage
        - Dockhand:
            href: http://docker.home.arpa
            icon: sh-dockhand
            server: homelab
            container: dockhand
        - Pi-Hole:
            href: http://dns.home.arpa
            icon: sh-pi-hole
            server: homelab
            container: pihole
            widget:
              type: pihole
              url: http://pihole:80
              version: 6
              key: "{{HOMEPAGE_VAR_PIHOLE_KEY}}"
              fields: ["queries", "blocked"]
        - File Browser:
            href: http://files.home.arpa
            icon: sh-file-browser
            server: homelab
            container: filebrowser
        - Caddy:
            icon: sh-caddy
            server: homelab
            container: caddy
            widget:
              type: caddy
              url: http://caddy:2019
        - Jellyfin:
            href: http://tv.home.arpa
            icon: sh-jellyfin
            server: homelab
            container: jellyfin
            widget:
              type: jellyfin
              url: http://jellyfin:8096
              key: "{{HOMEPAGE_VAR_JELLYFIN_API_KEY}}"
              enableBlocks: true
              enableNowPlaying: true
              enableUser: true
              enableMediaControl: false
              showEpisodeNumber: true
              expandOneStreamToTwoRows: false
        - Statistics for Strava:
            href: http://strava.home.arpa
            icon: sh-strava
            server: homelab
            container: statistics_for_strava
        - Tailscale:
            icon: sh-tailscale
            server: homelab
            container: tailscale
            widget:
              type: tailscale
              key: "{{HOMEPAGE_VAR_TAILSCALE_ACCESS_TOKEN}}"
              deviceid: "{{HOMEPAGE_VAR_TAILSCALE_DEVICE_ID}}"
        - Sonarr:
            href: http://sonarr.home.arpa
            icon: sh-sonarr
            server: homelab
            container: sonarr
            widget:
              type: sonarr
              url: http://sonarr:8989
              key: "{{HOMEPAGE_VAR_SONARR_API_KEY}}"
              enableQueue: true # optional, defaults to false
        - Radarr:
            href: http://radarr.home.arpa
            icon: sh-radarr
            server: homelab
            container: radarr
            widget:
              type: radarr
              url: http://radarr:7878
              key: "{{HOMEPAGE_VAR_RADARR_API_KEY}}"
              enableQueue: true # optional, defaults to false
        - Prowlarr:
            href: http://prowlarr.home.arpa
            icon: sh-prowlarr
            server: homelab
            container: prowlarr
            widget:
              type: prowlarr
              url: http://prowlarr:9696
              key: "{{HOMEPAGE_VAR_PROWLARR_API_KEY}}"
        - Jellyseerr:
            href: http://jellyseerr.home.arpa
            icon: sh-jellyseerr
            server: homelab
            container: jellyseerr
            widget:
              type: jellyseerr
              url: http://jellyseerr:5055
              key: "{{HOMEPAGE_VAR_JELLYSEERR_API_KEY}}"
        - Sabnzbd:
            href: http://sabnzbd.home.arpa
            icon: sh-sabnzbd
            server: homelab
            container: sabnzbd
            widget:
              type: sabnzbd
              url: http://sabnzbd:8080
              key: "{{HOMEPAGE_VAR_SABNZBD_API_KEY}}"

    - Outpost:
        - Alfa Males 2025:
            description: "Server hosted on Oracle Cloud with IP: {{HOMEPAGE_VAR_MINECRAFT_SERVER_IP}}."
            icon: sh-minecraft
            widget:
              type: gamedig
              serverType: minecraft
              url: udp://{{HOMEPAGE_VAR_MINECRAFT_SERVER_IP}}
              fields: ["status", "currentPlayers", "ping"]

    - External:
        - visard.me:
            description: "Personal portfolio and blog website."
            icon: https://visard.me/favicon.ico
            href: https://visard.me
            ping: https://visard.me

- Calendar:
    - Calendar:
        widgets:
          - type: calendar
            view: monthly
            showTime: true
            integrations:
              - type: ical
                name: Google Calendar
                url: "{{HOMEPAGE_VAR_GOOGLE_CALENDAR_ICAL_PRIVATE_URL}}"
                color: green
          - type: calendar
            view: agenda
            maxEvents: 15
            integrations:
              - type: ical
                name: Google Calendar
                url: "{{HOMEPAGE_VAR_GOOGLE_CALENDAR_ICAL_PRIVATE_URL}}"
                color: green
