---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/settings/

background:
  image: /images/lakehouse.jpg

theme: dark
color: neutral
statusStyle: basic
cardBlur: md
headerStyle: boxedWidgets
disableIndexing: true

layout:
  # Daily tab
  Calendar:
    tab: Daily
    header: false

  Bookmarks:
    tab: Daily
    header: false

  Streaming:
    tab: Daily
    style: row

  Finance:
    tab: Daily
    style: row
    columns: 2

  # Services tab
  Services:
    tab: Services
    style: row
    columns: 1
    header: false

    Homelab:
      style: row
      columns: 3
      useEqualHeights: true

    Outpost:
    External:

  Documentation:
    tab: Services
    style: row
    columns: 2
