---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/settings/

background:
  image: /images/lakehouse.jpg

theme: dark
color: neutral
statusStyle: basic
cardBlur: md
headerStyle: boxedWidgets
disableIndexing: true

layout:
  # Daily tab
  Calendar:
    header: false

  Bookmarks:
    header: false

  # Services tab
  Services:
    style: row
    columns: 1
    header: false

    Homelab:
      style: row
      columns: 3
      useEqualHeights: true

    External:

  Documentation:
    style: row
    columns: 2
