---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/info-widgets/

- resources:
    disk: /app/config
    uptime: true

- search:
    provider: duckduckgo
    target: _blank

- openmeteo:
    label: Katowice
    latitude: 50.1552
    longitude: 19.0125
    timezone: Europe/Warsaw
    units: metric
    cache: 30

- datetime:
    text_size: xl
    locale: pl-PL
    timezone: Europe/Warsaw
    format:
      timeStyle: medium
      hourCycle: h23
      dateStyle: short
