services:

  # DOCKHAND (DOCKER DASHBOARD)
  dockhand:
    image: fnsys/dockhand:latest
    container_name: dockhand
    restart: always
    ports:
      - 9443:3000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - dockhand_data:/app/data
      - /home/homelab/homelab:/home/homelab/homelab
    networks:
      - frontend

volumes:
  dockhand_data:
    name: dockhand_data

networks:
  frontend:
    name: frontend
    external: true
